"use client";

import { motion } from 'framer-motion';
import { User, Mic, Zap } from 'lucide-react';
import styles from './Services.module.css';

const services = [
  {
    id: 1,
    title: "Hyper-Realistic AI Avatars",
    description: "We generate lifelike AI avatars that act as the perfect face for your brand, speaking directly to your target audience with native fluency.",
    icon: <User size={32} />
  },
  {
    id: 2,
    title: "AI Voice Cloning",
    description: "Crystal clear, emotion-driven voiceovers generated by advanced AI to deliver your brand's script perfectly every single time.",
    icon: <Mic size={32} />
  },
  {
    id: 3,
    title: "High-Volume UGC Testing",
    description: "We rapidly produce dozens of creative variations so you can A/B test hooks and angles, allowing you to scale your winning ads instantly.",
    icon: <Zap size={32} />
  }
];

export default function Services() {
  return (
    <section className={styles.servicesSection} id="services">
      <div className="container">
        <div className={styles.header}>
          <motion.h2 
            className={styles.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
          >
            Our Capabilities
          </motion.h2>
          <motion.p 
            className={styles.subtitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            We specialize in diverse animation styles to ensure your message is delivered with maximum impact.
          </motion.p>
        </div>

        <div className={styles.grid}>
          {services.map((service, index) => (
            <motion.div 
              key={service.id}
              className={styles.card}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              <div className={styles.iconWrapper}>
                {service.icon}
              </div>
              <h3 className={styles.cardTitle}>{service.title}</h3>
              <p className={styles.cardDescription}>{service.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
